INSERT INTO BALANCE (ID, THEBALANCE) VALUES (1, 200);
INSERT INTO BALANCE (ID, THEBALANCE) VALUES (2, 200);
INSERT INTO BALANCE (ID, THEBALANCE) VALUES (3, 300);
INSERT INTO BALANCE (ID, THEBALANCE) VALUES (4, 400);
INSERT INTO BALANCE (ID, THEBALANCE) VALUES (5, 500);